server:
  port: 8000
  error:
    include-exception: true
    include-message: always

# spring配置
spring:
  redis:
    host: 8.210.72.249
    port: 6355
    password: Pv4boIgGgI0HCp3I
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.32.114.40:3306/eternal?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: EternalRoot123.
  servlet:
      multipart:
        enabled: true
        max-file-size: 2048MB
        max-request-size: 2048MB
mybatis-plus:
  type-aliases-package: com.eternal.domain
  mapper-locations: classpath:/mapper/*Mapper.xml
